spring.application.name=gss-inventory

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:gss_inventory}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:gss_inventory}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:gss_inventory}}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
